eureka:
  client:
    serviceUrl:
      defaultZone: "http://172.18.2.45:8900/eureka"
    register-with-eureka: true
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 20
    prefer-ip-address: true
    instance-id: "${spring.cloud.client.ip-address}:${server.port}"

druid:
  configPath:  /data/gtobasicdb_dev.properties