app:
  id: 10000009
info:
  app:
    name: 实体ID服务
    version: 1.0.0
    description: 提供实体ID调用接口

logging:
  level:
      org.slf4j.Logger: fatal #TRACE,DEBUG,INFO,WARN,ERROR,FATAL,OFF


server:
  port: 8805
  session-timeout: "# session timeout in seconds"
  tomcat:
    background-processor-delay: 30s
    basedir: /tmp
    max-threads: 0
    protocol-header: x-forwarded-proto
    remote-ip-header: x-forwarded-for
    uri-encoding: UTF-8

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  application:
    name: entityid-sync-service
  http:
    encoding:
      force: true
  converters:
    preferred-json-mapper: jackson
  jackson:
    default-property-inclusion: non_null
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    min: 5
    max: 30
    validation-query: "SELECT 1"
    max-wait: 10000
    max-idle: 10
    min-idle: 5
    max_active: 50
    initial-size: 5
    test-on-borrow: false
    test-while-idle: true
    remove_abandoned: true
    remove_abandoned_timeout: 180
    time-between-eviction-runs-millis: 18800
  # Redis数据库索引（默认为0）
  redis:
    counterredis:
      database: 0
    # Redis服务器地址
      host: 172.18.2.45
    # Redis服务器连接端口
      port: 6378
    # 连接池最大连接数（使用负值表示没有限制）
      pool:
        max-active: 200
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
    # 连接池中的最大空闲连接
        max-idle: 10
    # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
      timeout: 1000
      password:
    transcriptredis:
      database: 0
      # Redis服务器地址
      host: 172.18.2.45
      # Redis服务器连接端口
      port: 6377
      # 连接池最大连接数（使用负值表示没有限制）
      pool:
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接超时时间（毫秒）
      timeout: 1000
      password:

  mvc:
    view:
      prefix: /
      suffix: .jsp
  thymeleaf:
      cache: false
      servlet:
        content-type: text/html
      encoding: UTF-8
      mode: HTML5
redisson:
  address: redis://172.18.2.45:6377
  password:

mybatis-plus:
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
  global-config:
  #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 1
    #驼峰下划线转换
    db-column-underline: true
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #刷新mapper 调试神器
    refresh-mapper: true
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  mapper-locations: mapper/*Mapper.xml
